name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps for your build process, such as installing dependencies and running tests

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes successfully before deploying
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to deploy your application, such as copying files to a server or deploying to a cloud platform
