name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps for your build process, such as installing dependencies and running tests

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes successfully before deploying
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: 192.168.30.147
          username: ${{ secrets.root }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # or your SSH port
          local: "."  # path to your local directory or files to deploy
          remote: "/var/www/html"  # path to the directory on the production server
