name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps for your build process, such as installing dependencies and running tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add OpenVPN repository and install OpenVPN3
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:openvpn/epel
          sudo apt-get update
          sudo apt-get install -y openvpn3

      - name: Start OpenVPN3
        run: |
          openvpn3 session-start --config vpn/vpn-config.ovpn || (openvpn3 session-status && exit 1)
          sleep 30  # Wait for the VPN connection to establish

      - name: Verify VPN connection
        run: |
          ip a
          curl ifconfig.me
          curl -k https://example.com  # Replace with a URL accessible only via VPN
        continue-on-error: true

      - name: Deploy to Production Server
        if: success() && always()  # Ensure this step runs only if the previous steps succeed
        uses: easingthemes/ssh-deploy@v2
        with:
          server: 192.168.30.147
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local: "."
          remote: "/var/www/html"
